maxims = """Know thyself (Γνῶθι σεαυτόν)
Nothing in excess (Μηδὲν ἄγαν)
Make a pledge and mischief is night (Ἐγγύα πάρα δ' Ἄτα)
Follow God (Επου θεω)
Obey the law (Νομω πειθου)
Worship the Gods (Θεους σεβου)
Respect your parents (Γονεις αιδου)
Be overcome by justice (Ηττω υπο δικαιου)
Know what you have learned (Γνωθι μαθων)
Perceive what you have heard (Ακουσας νοει)
Be (or Know) Yourself (Σαυτον ισθι)
Intend to get married (Γαμειν μελλε)
Know your opportunity (Καιρον γνωθι)
Think as a mortal (Φρονει θνητα)
If you are a stranger act like one (Ξepsilon;νος ων ισθι)
Honor the hearth [or Hestia] (Εστιαν τιμα)
Control yourself (Αρχε σεαυτου)
Help your friends (Φιλοις βοηθει)
Control anger (Θυμου κρατει)
Exercise prudence (Φρονησιν ασκει)
Honor providence (Προνοιαν τιμα)
Do not use an oath (Ορκω μη χρω)
Love friendship (Φιλιαν αγαπα)
Cling to discipline (Παιδειας αντεχου)
Pursue honor (Δοξαν διωκε)
Long for wisdom (Σοφιαν ζηλου)
Praise the good (Καλον ευ λεγε)
Find fault with no one (Ψεγε μηδενα)
Praise virtue (Επαινει αρετην)
Practice what is just (Πραττε δικαια)
Be kind to friends (Θιλοις ευνοει)
Watch out for your enemies (Εχθρους αμυνου)
Exercise nobility of character (Ευγενειαν ασκει)
Shun evil (Κακιας απεχου)
Be impartial (Κοινος γινου)
Guard what is yours (Ιδια φυλαττε)
Shun what belongs to others (Αλλοτριων απεχου)
Listen to everyone (Ακουε παντα)
Be (religiously) silent (Ευφημος ιοθι)
Do a favor for a friend (Φιλω χαριζου)
Nothing to excess (Μηδεν αγαν)
Use time sparingly (Χρονου φειδου)
Foresee the future (Ορα το μελλον)
Despise insolence (Υβριν μισει)
Have respect for suppliants (Ικετας αιδου)
Be accommodating in everything (Παςιν αρμοζου)
Educate your sons (Υιους παιδευε)
Give what you have (Εχων χαριζου)
Fear deceit (Δολον φοβου)
Speak well of everyone (Ευλογει παντας)
Be a seeker of wisdom (Φιλοσοφος γινου)
Choose what is divine (Οσια κρινε)
Act when you know (Γνους πραττε)
Shun murder (Φονου απεχου)
Pray for things possible (Ευχου δυνατα)
Consult the wise (Σοφοις χρω)
Test the character (Ηθος δοκιμαζε)
Give back what you have received (Λαβων αποδος)
Down-look no one (Υφορω μηδενα)
Use your skill (Τεχνη χρω)
Do what you mean to do (Ο μελλεις, δος)
Honor a benefaction (Ευεργεςιας τιμα)
Be jealous of no one (Φθονει μηδενι)
Be on your guard (Φυλακη προσεχε)
Praise hope (Ελπιδα αινει)
Despise a slanderer (Διαβολην μισει)
Gain possessions justly (Δικαιως κτω)
Honor good men (Αγαθους τιμα)
Know the judge (Κριτην γνωθι)
Master wedding-feasts (Γαμους κρατει)
Recognize fortune (Τυχην νομιζε)
Flee a pledge (Εγγυην φευγε)
Speak plainly (Αμλως διαλεγου)
Associate with your peers (Ομοιοις χρω)
Govern your expenses (Δαπανων αρχου)
Be happy with what you have (Κτωμενος ηδου)
Rever a sense of shame (Αισχυνην σεβου)
Fulfill a favor (Χαριν εκτελει)
Pray for happiness (Ευτυχιαν ευχου)
Be fond of fortune (Τυχην στεργε)
Observe what you have heard (Ακουων ορα)
Work for what you can own (Εργαζου κτητα)
Despise strife (Εριν μισει)
Detest disgrace (Ονειδς εχθαιρε)
Restrain the tongue (Γλωτταν ισχε)
Keep yourself from insolence (Υβριν αμυνου)
Make just judgments (Κρινε δικαια)
Use what you have (Χρω χρημασιν)
Judge incorruptibly (Αδωροδοκητος δικαζε)
Accuse one who is present (Αιτιω παροντα)
Tell when you know (Λεγε ειδως)
Do not depend on strength (Βιας μη εχου)
Live without sorrow (Αλυπως βιου)
Live together meekly (Ομιλει πραως)
Finish the race without shrinking back (Περας επιτελει μη αποδειλιων))
Deal kindly with everyone (Φιλοφρονει πασιν)
Do not curse your sons (Υιοις μη καταρω)
Guide your wife (Γυναικος αρχε)
Benefit yourself (Σεαυτον ευ ποιει)
Be courteous (Ευπροσηγορος γινου)
Give a timely response (Αποκρινου εν καιρω)
Struggle with glory (Πονει μετ ευκλειας)
Act without repenting (Πραττε αμετανοητως)
Repent of sins (Αμαρτανων μετανοει)
Control the eye (Οφθαλμοθ κρατει)
Give a timely counsel (Βουλευου χρονω)
Act quickly (Πραττε συντομως)
Guard friendship (Φιλιαν φυλαττε)
Be grateful (Ευγνωμων γινου)
Pursue harmony (Ομονοιαν διωκε)
Keep deeply the top secret (Αρρητον κρυπτε)
Fear ruling (Το κρατουν φοβου)
Pursue what is profitable (Το συμφερον θηρω)
Accept due measure (Καιρον προσδεχου)
Do away with enmities (Εχθρας διαλυε)
Accept old age (Γηρας προσδεχου)
Do not boast in might (Επι ρωμη μη καυχω)
Exercise (religious) silence (Ευφημιαν ασκει)
Flee enmity (Απεχθειαν φευγε)
Acquire wealth justly (Πλουτει δικιως)
Do not abandon honor (Δοξαν μη λειπε)
Despise evil (Κακιαν μισει)
Venture into danger prudently (Κινδυνευε φρονιμως)
Do not tire of learning (Μανθανων μη καμνε)
Do not stop to be thrifty (Φειδομενος μη λειπε)
Admire oracles (Χρησμους θαυμαζε)
Love whom you rear (Ους τρεφεις αγαπα)
Do not oppose someone absent (Αποντι μη μαχου)
Respect the elder (Πρεσβυτερον αιδου)
Teach a youngster (Νεωτερον διδασκε)
Do not trust wealth (Πλουτω απιστει)
Respect yourself (Σεαυτον αιδου)
Do not begin to be insolent (Μη αρχε υβριζειν)
Crown your ancestors (Προγονους στεφανου)
Die for your country (Θνησκε υπερ πατριδος)
Do not be discontented by life (Τω βιω μη αχθου)
Do not make fun of the dead (Επι νεκρω μη γελα)
Share the load of the unfortunate (Ατυχουντι συναχθου)
Gratify without harming (Χαριζου αβλαβως)
Grieve for no one (Μη επι παντι λυπου)
Beget from noble routes (Εξ ευγενων γεννα)
Make promises to no one (Επαγγελου μηδενι)
Do not wrong the dead (Φθιμενους μη αδικει)
Be well off as a mortal (Ευ πασχε ως θνητος)
Do not trust fortune (Τυχη μη πιστευε)
As a child be well-behaved (Παις ων κοσμιος ισθι)
as a youth – self-disciplined (ηβων εγκρατης)
as of middle-age – just (μεσος δικαιος)
as an old man – sensible (πρεσβυτης ευλογος)
on reaching the end – without sorrow (τελευτων αλυπος)""".split('\n')
